server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /controlOperativo-backend
spring:
  config:
    import: optional:file:/etc/springboot-env/.env[.properties]
    
  datasource:
    control-operativo:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST_CO}/${DB_SCHEMA_CO}
      username: ${USERNAME_CO}
      password: ${PASSWORD_CO}
      hibernate-hbm2ddl-auto: update
      show-sql: true
    soa-alt:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_ALT}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-chb:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_CHB}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-vir:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_VIR}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-scz:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_SCZ}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-tam:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_TAM}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-scr:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_SCR}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-yac:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_YAC}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-vil:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_VIL}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-ava:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_AVA}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-ber:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_BER}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-psg:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_PSG}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: ${SIGNIN_KEY}
  encoding-strength: ${ENCODING_STRENGTH}
  security-realm: Spring Boot JWT
  jwt:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    grant-type: ${GRANT_TYPE}
    scope-read: read
    scope-write: write
    resource-ids: ${RESOURCE_ID}
property: false
suma:
  api:
    host:
      baseUrl: https://suma.aduana.gob.bo
