server:
  port: 8080
  address: localhost
  servlet:
    context-path: /controlOperativo-backend
spring:
  datasource:
    control-operativo:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST_CO}/control-operativo
      username: controlop
      password: ${PASSWORD_CO}
      hibernate-hbm2ddl-auto: update
      show-sql: true
    soa-alt:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.224.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-chb:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.226.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-vir:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.221.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-scz:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.223.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-tam:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.205.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-scr:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.208.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-yac:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.225.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-vil:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.227.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-ava:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.210.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-ber:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.209.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-psg:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.207.5:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: ${SIGNIN_KEY}
  encoding-strength: 256
  security-realm: Spring Boot JWT
  jwt:
    client-id: controlOperativo
    client-secret: ${CLIENT_SECRET}
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: ${RESOURCE_ID}
property: false
suma:
  api:
    host:
      baseUrl: https://suma.aduana.gob.bo
