package com.albo.soa.repository;

import java.math.BigInteger;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.albo.soa.model.VInventarioEgr;

public interface IVInventarioEgrRepository extends JpaRepository<VInventarioEgr, BigInteger> {

	@Query(value = "SELECT ROWNUM ID_COD,\r\n"
			+ "         inv.inv_parte INV_PARTE,\r\n"
			+ "         inv.inv_nro INV_NRO,\r\n"
			+ "         inv.inv_recinto INV_RECINTO,\r\n"
			+ "         inv.inv_aduana INV_ADUANA,\r\n"
			+ "         inv.inv_gestion INV_GESTION,\r\n"
			+ "         inv.inv_nroreg INV_NROREG,\r\n"
			+ "         inv.inv_fecha INV_FECHA,\r\n"
			+ "         inv.inv_fecha_anpr INV_FECHA_ANPR,\r\n"
			+ "         inv.inv_fechaing INV_FECHAING,\r\n"
			+ "         inv.inv_estado INV_ESTADO,\r\n"
			+ "         tdt.tra_cod TRA_COD,\r\n"
			+ "         tdt.trd_descripcion TRA_DESCRIPCION,\r\n"
			+ "         tmer.tme_cod TME_COD,\r\n"
			+ "         tmer.tme_nombre TME_NOMBRE,\r\n"
			+ "         tmerd.dtm_cod DTM_COD,\r\n"
			+ "         tmerd.dtm_nombre DTM_NOMBRE,\r\n"
			+ "         invd.din_cod DIN_COD,\r\n"
			+ "         invd.din_descripcion DIN_DESCRIPCION,\r\n"
			+ "         inv.inv_embarque INV_EMBARQUE,\r\n"
			+ "         inv.inv_nitcons INV_NITCONS,\r\n"
			+ "         inv.inv_nomcons INV_NOMCONS,\r\n"
			+ "         tb.tbu_cod TBU_COD,\r\n"
			+ "         tb.tbu_nombre TBU_NOMBRE,\r\n"
			+ "         invd.din_bultos DIN_BULTOS,\r\n"
			+ "         invd.din_peso DIN_PESO,\r\n"
			+ "         invs.bulto_s BULTO_S,\r\n"
			+ "         invs.peso_s PESO_S,\r\n"
			+ "         inv.localizacion LOCALIZACION,\r\n"
			+ "         alm.alm_cod ALM_COD,\r\n"
			+ "         alm.alm_nombre ALM_NOMBRE,\r\n"
			+ "         ubi.ubi_cod UBI_COD,\r\n"
			+ "         ubi.ubi_nombre UBI_NOMBRE,\r\n"
			+ "         inv.inv_obs INV_OBS,\r\n"
			+ "         s.inv_parte INV_PARTE_S,\r\n"
			+ "         s.din_cod DIN_COD_S,\r\n"
			+ "         s.sal_cod SAL_COD,\r\n"
			+ "         s.sal_fecha SAL_FECHA,\r\n"
			+ "         s.dos_cod DOS_COD,\r\n"
			+ "         s.dsd_bulto DSD_BULTO,\r\n"
			+ "         s.dsd_peso DSD_PESO,\r\n"
			+ "         s.pat_cod PAT_COD,\r\n"
			+ "         s.pk_item PK_ITEM_S,\r\n"
			+ "         (invd.din_bultos - invs.bulto_s) BULTO_SALDO,\r\n"
			+ "         (invd.din_peso - invs.peso_s) PESO_SALDO,\r\n"
			+ "         inv.inv_bulto_rec INV_BULTO_REC,\r\n"
			+ "         inv.inv_peso_rec INV_PESO_REC,\r\n"
			+ "         inv.inv_bulto_saldo INV_BULTO_SALDO,\r\n"
			+ "         inv.inv_peso_saldo INV_PESO_SALDO,\r\n"
			+ "         s.tipo_sal TIPO_SAL,\r\n"
			+ "         inv.trd_cod TRD_COD,\r\n"
			+ "         INV.USR_COD USR_COD,\r\n"
			+ "         s.SAL_USR SAL_USR\r\n"
			+ "    FROM inventario inv\r\n"
			+ "         LEFT JOIN inventario_det invd\r\n"
			+ "            ON (inv.inv_parte = invd.inv_parte)\r\n"
			+ "         LEFT JOIN tratamiento_deposito_det tdt\r\n"
			+ "            ON (inv.tra_cod = tdt.tra_cod AND inv.trd_cod = tdt.trd_cod)\r\n"
			+ "         LEFT JOIN tipo_mercancia tmer\r\n"
			+ "            ON (invd.tme_cod = tmer.tme_cod)\r\n"
			+ "         LEFT JOIN tipo_mercancia_det tmerd\r\n"
			+ "            ON (invd.tme_cod = tmerd.tme_cod AND invd.dtm_cod = tmerd.dtm_cod)\r\n"
			+ "         LEFT JOIN tipo_bulto tb\r\n"
			+ "            ON (invd.tbu_cod = tb.tbu_cod)\r\n"
			+ "         LEFT JOIN v_inventario_saldo invs\r\n"
			+ "            ON (inv.inv_parte = invs.inv_parte AND invd.din_cod = invs.din_cod)\r\n"
			+ "         LEFT JOIN almacen alm\r\n"
			+ "            ON (inv.inv_recinto = alm.rec_cod AND invd.alm_cod = alm.alm_cod)\r\n"
			+ "         LEFT JOIN ubicacion ubi\r\n"
			+ "            ON (    invd.rec_cod = ubi.rec_cod\r\n"
			+ "                AND invd.ubi_cod = ubi.ubi_cod\r\n"
			+ "                AND invd.alm_cod = ubi.alm_cod)\r\n"
			+ "         LEFT JOIN (SELECT TIPO_SAL,\r\n"
			+ "                           DSD_COD,\r\n"
			+ "                           INV_PARTE,\r\n"
			+ "                           DIN_COD,\r\n"
			+ "                           SAL_COD,\r\n"
			+ "                           PK_ITEM,\r\n"
			+ "                           SAL_FECHA,\r\n"
			+ "                           DOS_COD,\r\n"
			+ "                           DSD_BULTO,\r\n"
			+ "                           DSD_PESO,\r\n"
			+ "                           PAT_COD,\r\n"
			+ "                           SAL_USR\r\n"
			+ "                      FROM ( (SELECT 'DES' tipo_sal,\r\n"
			+ "                                     DD.dsd_cod,\r\n"
			+ "                                     i.inv_parte,\r\n"
			+ "                                     i.din_cod,\r\n"
			+ "                                     DD.sal_cod,\r\n"
			+ "                                     DD.pk_item,\r\n"
			+ "                                     ds.sal_fecha,\r\n"
			+ "                                     DD.dos_cod,\r\n"
			+ "                                     dsd_bulto,\r\n"
			+ "                                     dsd_peso,\r\n"
			+ "                                     DD.pat_cod,\r\n"
			+ "                                     DS.SAL_USR\r\n"
			+ "                                FROM DOC_SALIDA_ENTREGA ds\r\n"
			+ "                                     INNER JOIN doc_salida_det DD\r\n"
			+ "                                        ON     ds.SAL_COD = dd.sal_cod\r\n"
			+ "                                           AND ds.sal_gestion = dd.sal_gestion\r\n"
			+ "                                           AND ds.sal_estado = 'ACT'\r\n"
			+ "                                           AND doc_tipo = 'INV'\r\n"
			+ "                                     INNER JOIN inventario_det i\r\n"
			+ "                                        ON     i.inv_parte = DD.pk\r\n"
			+ "                                           AND i.din_cod = DD.pk_item\r\n"
			+ "                                           AND inv_estado = 'ACT'\r\n"
			+ "                               WHERE TRUNC (ds.SAL_FECHA) <=\r\n"
			+ "                                        TO_DATE (:fechaSalida, 'DD/MM/YYYY'))\r\n"
			+ "                            UNION\r\n"
			+ "                            (SELECT 'INV' tipo_sal,\r\n"
			+ "                                    0,\r\n"
			+ "                                    d1.inv_parte,\r\n"
			+ "                                    d1.din_cod,\r\n"
			+ "                                    d2.inv_nro,\r\n"
			+ "                                    d2.din_cod,\r\n"
			+ "                                    d2.inv_fecha,\r\n"
			+ "                                    d2.inv_parte,\r\n"
			+ "                                    d2.din_bultos,\r\n"
			+ "                                    d2.din_peso,\r\n"
			+ "                                    '',\r\n"
			+ "                                    ''\r\n"
			+ "                               FROM    inventario_det d1\r\n"
			+ "                                    INNER JOIN\r\n"
			+ "                                       inventario_det d2\r\n"
			+ "                                    ON     d1.inv_parte = d2.inv_partem\r\n"
			+ "                                       AND d1.din_cod = d2.din_codm\r\n"
			+ "                              WHERE     d1.inv_estado = 'ACT'\r\n"
			+ "                                    AND d2.inv_estado = 'ACT'\r\n"
			+ "                                    AND TRUNC (d2.inv_fecha) <=\r\n"
			+ "                                           TO_DATE (:fechaSalida, 'DD/MM/YYYY')))) s\r\n"
			+ "            ON inv.inv_parte = s.inv_parte AND invd.din_cod = s.din_cod\r\n"
			+ "   WHERE     inv.inv_recinto = :recinto\r\n"
			+ "         AND inv.inv_estado = :estado\r\n"
			+ "         AND (    TRUNC (inv.inv_fecha) >= TO_DATE (:fechaInicial, 'DD/MM/YYYY')\r\n"
			+ "              AND TRUNC (inv.inv_fecha) <= TO_DATE (:fechaFinal, 'DD/MM/YYYY'))\r\n"
			+ "ORDER BY inv.inv_fecha_anpr ASC,\r\n"
			+ "         inv.inv_parte ASC,\r\n"
			+ "         invd.din_cod ASC,\r\n"
			+ "         s.sal_cod ASC,\r\n"
			+ "         s.pk_item", 
			  nativeQuery = true)
	List<VInventarioEgr> listarVInventarioEgr(
			@Param("fechaSalida") String fechaSalida, 
			@Param("recinto") String recinto, 
			@Param("estado") String estado,
			@Param("fechaInicial") String fechaInicial,
			@Param("fechaFinal") String fechaFinal);
	
}
